// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk67bgk7AnBMM_iHpEtGVNY32f0uD3Bl0',
    appId: '1:899024667872:web:92cc50f5d414703bcf3c85',
    messagingSenderId: '899024667872',
    projectId: 'spotify0101-c2e01',
    authDomain: 'spotify0101-c2e01.firebaseapp.com',
    storageBucket: 'spotify0101-c2e01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuFuMGS71XNQ9klkBB7UXQWqtHfNocPk',
    appId: '1:899024667872:android:d0190adfbbf9fb84cf3c85',
    messagingSenderId: '899024667872',
    projectId: 'spotify0101-c2e01',
    storageBucket: 'spotify0101-c2e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ8bpmdtQJ7dU2hCYKGjCd1Hhrw0HRqno',
    appId: '1:899024667872:ios:89ea3cfd92e1231ecf3c85',
    messagingSenderId: '899024667872',
    projectId: 'spotify0101-c2e01',
    storageBucket: 'spotify0101-c2e01.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ8bpmdtQJ7dU2hCYKGjCd1Hhrw0HRqno',
    appId: '1:899024667872:ios:89ea3cfd92e1231ecf3c85',
    messagingSenderId: '899024667872',
    projectId: 'spotify0101-c2e01',
    storageBucket: 'spotify0101-c2e01.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk67bgk7AnBMM_iHpEtGVNY32f0uD3Bl0',
    appId: '1:899024667872:web:1ed31b98910011f3cf3c85',
    messagingSenderId: '899024667872',
    projectId: 'spotify0101-c2e01',
    authDomain: 'spotify0101-c2e01.firebaseapp.com',
    storageBucket: 'spotify0101-c2e01.firebasestorage.app',
  );
}
